CREATE OR REPLACE PROCEDURE MY_ITEMS(ID IN VARCHAR, PRICE NUMBER)
IS
  BEGIN
    DECLARE
      NOOFITEMS NUMBER;
    BEGIN
      IF PRICE <= 0 THEN
        NOOFITEMS := 0;

      ELSIF PRICE > 1000 THEN
        NOOFITEMS := NOOFITEMS+2;
        
      ELSIF PRICE = 10 THEN
        NOOFITEMS := NOOFITEMS+1;
      ELSE
        NOOFITEMS := 0;
      
      END IF;


      INSERT INTO ITEM_TABLE(ITEM_ID, ITEM_PRICE, ITEM_COUNT)
      VALUES (ID, PRICE, NOOFITEMS);

    END;
  
  END;