 CREATE OR REPLACE PROCEDURE PROC_BUDGET_ADJUST (DEPARTMENT_ID INT, AVAIL_AMT INT) 
 IS 
 	PROPOSED_AMT INT;
 	EXTRA INT;
 	DECRS INT;
 	NO_ATTR INT;
 	
 	BEGIN
 		NO_ATTR := 4;
 		SELECT TOTAL_AMT INTO PROPOSE_AMT
		FROM BUDGET_TAB WHERE DEPT_ID = DEPARTMENT_ID;
 		IF (PROPOSE_AMT >= AVAIL_AMT) THEN
   			EXTRA := PROPOSE_AMT - AVAIL_AMT;
  			DECRS := EXTRA/NO_ATTR;
  		UPDATE BUDGET_TAB SET MANPOWER = MANPOWER - DECRS, EQUIPMENT = EQUIPMENT - DECRS, CONTINGENCY = CONTINGENCY - DECRS, CONSUMABLE = CONSUMABLE - DECRS
 		WHERE DEPT_ID = DEPARTMENT_ID;
 		END IF;
 	ASSERT MANPOWER > 0;
 END;
