CREATE OR REPLACE PROCEDURE MY_ITEMS(ID IN VARCHAR, NO_OF_ITEMS NUMBER)
IS
  BEGIN
    DECLARE
      PRICE NUMBER;
    BEGIN
      SELECT ITEM_PRICE INTO PRICE FROM ITEM_TABLE WHERE ITEM_ID = ID;
      IF NO_OF_ITEMS >= 1000 THEN
        PRICE := PRICE - 0.1*NO_OF_ITEMS;

      ELSIF NO_OF_ITEMS >= 500 THEN
        PRICE := PRICE - 0.2*NO_OF_ITEMS;
        
      ELSIF NO_OF_ITEMS > 99 AND PRICE > 5000 THEN
        PRICE := PRICE - 0.2*NO_OF_ITEMS;
      ELSE
        PRICE := PRICE + 0.05*NO_OF_ITEMS;
      
      END IF;


      INSERT INTO ITEM_TABLE(ITEM_ID, ITEM_PRICE, ITEM_COUNT)
      VALUES (ID, PRICE, NO_OF_ITEMS);

    END;
  
  END;