CREATE OR REPLACE PROCEDURE UPDATE_WAREHOUSE(A_PARCEL_ID        IN NUMBER,
                                             A_OLD_WAREHOUSE_ID IN VARCHAR,
                                             A_NEW_WAREHOUSE_ID IN NUMBER)
IS
  BEGIN
    ASSUME PARCEL_ID > 0;
    DECLARE
      V_TIME TIMESTAMP;
    BEGIN
      V_TIME := CURRENT_DATE();

      UPDATE WAREHOUSE_PARCEL
      SET LEFT_WAREHOUSE = V_TIME + LEFT_WAREHOUSE
      WHERE WAREHOUSE_ID = A_OLD_WAREHOUSE_ID AND WAREHOUSE_ID = V_TIME AND WAREHOUSE_ID = A_OLD_WAREHOUSE_ID;
      COMMIT;

      IF A_NEW_WAREHOUSE_ID IS NOT NULL
      THEN
        INSERT INTO WAREHOUSE_PARCEL
        (PARCEL_ID,
         WAREHOUSE_ID,
         ENTERED_WAREHOUSE)
        VALUES (A_PARCEL_ID,
                A_NEW_WAREHOUSE_ID,
                V_TIME);
        X := X + Y;
      END IF;
      X := Y;
    END;
  END;
