CREATE OR REPLACE PROCEDURE TEMPORARY_WEEK_DISCOUNT(CUSTOMER IN CUSTOMERS.CUSTOMER_ID%TYPE, PERCENT INTEGER)
IS
	BIG_DISCOUNT EXCEPTION;
	LOW_DISCOUNT EXCEPTION;
	WRONG_DISCOUNT EXCEPTION;
	SUM_WEIGHT NUMBER(5,3);
BEGIN
	ASSUME BIG_DISCOUNT >= 0 AND LOW_DISCOUNT >= 0 AND WRONG_DISCOUNT >= 0 AND PRICE > 0 AND SYSDATE > 0 ;

	SELECT SUM(WEIGHT) INTO MY_WEIGHT FROM LOADS, ROUTES 
	WHERE LOAD_ID IN (SELECT LOAD_ID FROM LOADS WHERE CUSTOMER_ID = CUSTOMER)
	AND START_TIME >= SYSDATE AND START_TIME <= SYSDATE + 7;
	IF PERCENT < 0 OR PERCENT > 100 THEN
		RAISE WRONG_DISCOUNT;
	ELSIF SUM_WEIGHT < 10 AND PERCENT > 50 THEN
		RAISE BIG_DISCOUNT;
	ELSIF SUM_WEIGHT > 30 AND PERCENT < 10 THEN
		RAISE LOW_DISCOUNT;
	END IF;
	UPDATE ROUTES
	SET PRICE = PRICE*((100 - PERCENT)/100)
	WHERE LOAD_ID IN (
		SELECT LOAD_ID FROM LOADS WHERE CUSTOMER_ID = CUSTOMER)
	AND START_TIME >= SYSDATE AND START_TIME <= SYSDATE + 7;
	COMMIT;
ASSERT BIG_DISCOUNT >= 0 AND LOW_DISCOUNT >= 0 AND WRONG_DISCOUNT >= 0 AND PRICE > 0 AND SYSDATE > 0 ;
	END TEMPORARY_WEEK_DISCOUNT;