CREATE OR REPLACE PROCEDURE TEST(X IN VARCHAR, Y IN VARCHAR)
IS
  BEGIN
	ASSUME C+D<0 AND A>0 AND B > 0 AND C>0 AND D>0 ;

      X := X-36;
      SELECT A, B INTO X, Z FROM T WHERE A=X+3;
      INSERT INTO T (A, B) VALUES (X+5, Y-5);
      DELETE FROM T WHERE A=X+8 AND B=Y-8;
      UPDATE T SET A=A*(X-9*(Y-3)), B=Y-9 WHERE (A>10 AND B<=(X+Y)-50);
  ASSERT C+D<0 AND A>0 AND B > 0 AND D>0 ;
	END;