# This file was generated at runtime 
from z3 import *

LOADS0 = Real('LOADS0')
LOW_DISCOUNT0 = Real('LOW_DISCOUNT0')
LOW_DISCOUNT2 = Real('LOW_DISCOUNT2')
WRONG_DISCOUNT2 = Real('WRONG_DISCOUNT2')
BIG_DISCOUNT2 = Real('BIG_DISCOUNT2')
SUM_OF_MAX1 = Real('SUM_OF_MAX1')
SUM_WEIGHT0 = Real('SUM_WEIGHT0')
PRICE0 = Real('PRICE0')
PERCENT0 = Real('PERCENT0')
PRICE1 = Real('PRICE1')
BIG_DISCOUNT0 = Real('BIG_DISCOUNT0')
SUM_WEIGHT1 = Real('SUM_WEIGHT1')
WRONG_DISCOUNT1 = Real('WRONG_DISCOUNT1')
ROUTES0 = Real('ROUTES0')
CUSTOMER0 = Real('CUSTOMER0')
WRONG_DISCOUNT3 = Real('WRONG_DISCOUNT3')
BIG_DISCOUNT1 = Real('BIG_DISCOUNT1')
START_TIME0 = Real('START_TIME0')
SYSDATE0 = Real('SYSDATE0')
BIG_DISCOUNT3 = Real('BIG_DISCOUNT3')
SUM_OF_MAX0 = Real('SUM_OF_MAX0')
LOAD_ID0 = Real('LOAD_ID0')
CUSTOMER_ID0 = Real('CUSTOMER_ID0')
WRONG_DISCOUNT0 = Real('WRONG_DISCOUNT0')
LOW_DISCOUNT1 = Real('LOW_DISCOUNT1')

s = Solver()
s.add(True)
s.add(Implies( True, And( ( SUM_OF_MAX0 ) == ( SUM_WEIGHT1 ), And( And( And( ( LOADS0 . LOAD_ID0 ) == ( LOAD_ID0 ), CUSTOMER_ID0 = CUSTOMER0 ), START_TIME0 >= SYSDATE0 ), START_TIME0 <= SYSDATE0 + 7 ) ) ))
s.add(Or( PERCENT < 0, PERCENT > 100 ))
s.add(Implies( Or( PERCENT < 0, PERCENT > 100 ), ( WRONG_DISCOUNT1 ) == ( 1 ) ))
s.add(Or( PERCENT < 0, PERCENT > 100 ))
s.add(Implies( Or( PERCENT < 0, PERCENT > 100 ), LOW_DISCOUNT1 == LOW_DISCOUNT0 ))
s.add(Or( PERCENT < 0, PERCENT > 100 ))
s.add(Implies( Or( PERCENT < 0, PERCENT > 100 ), BIG_DISCOUNT1 == BIG_DISCOUNT0 ))
s.add(Or( PERCENT < 0, PERCENT > 100 ))
s.add(Implies( Or( PERCENT < 0, PERCENT > 100 ), WRONG_DISCOUNT2 == WRONG_DISCOUNT1 ))
s.add(And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( SUM_WEIGHT < 10, PERCENT > 50 ) ))
s.add(Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( SUM_WEIGHT < 10, PERCENT > 50 ) ), ( BIG_DISCOUNT2 ) == ( 1 ) ))
s.add(And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( SUM_WEIGHT < 10, PERCENT > 50 ) ))
s.add(Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( SUM_WEIGHT < 10, PERCENT > 50 ) ), LOW_DISCOUNT1 == LOW_DISCOUNT0 ))
s.add(And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( SUM_WEIGHT < 10, PERCENT > 50 ) ))
s.add(Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( SUM_WEIGHT < 10, PERCENT > 50 ) ), BIG_DISCOUNT1 == BIG_DISCOUNT2 ))
s.add(And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( SUM_WEIGHT < 10, PERCENT > 50 ) ))
s.add(Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( SUM_WEIGHT < 10, PERCENT > 50 ) ), WRONG_DISCOUNT2 == WRONG_DISCOUNT0 ))
s.add(And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ))
s.add(Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ), ( LOW_DISCOUNT2 ) == ( 1 ) ))
s.add(And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ))
s.add(Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ), LOW_DISCOUNT1 == LOW_DISCOUNT2 ))
s.add(And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ))
s.add(Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ), BIG_DISCOUNT1 == BIG_DISCOUNT0 ))
s.add(And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ))
s.add(Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ), WRONG_DISCOUNT2 == WRONG_DISCOUNT0 ))
s.add(And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ))
s.add(Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ), ( WRONG_DISCOUNT3 ) == ( 0 ) ))
s.add(And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ))
s.add(Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ), ( BIG_DISCOUNT3 ) == ( 0 ) ))
s.add(And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ))
s.add(Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ), LOW_DISCOUNT1 == LOW_DISCOUNT0 ))
s.add(And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ))
s.add(Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ), BIG_DISCOUNT1 == BIG_DISCOUNT3 ))
s.add(And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ))
s.add(Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ), WRONG_DISCOUNT2 == WRONG_DISCOUNT3 ))
s.add(True)
s.add(Implies( True, Or( And( ( PRICE1 ) == ( PRICE0 * ( ( 100 - PERCENT0 ) / 100 ) ), And( And( And( ( ROUTES0 . LOAD_ID0 ) == ( LOAD_ID0 ), CUSTOMER_ID0 = CUSTOMER0 ), START_TIME0 >= SYSDATE0 ), START_TIME0 <= SYSDATE0 + 7 ) ), And( Not( And( And( And( ( ROUTES0 . LOAD_ID0 ) == ( LOAD_ID0 ), CUSTOMER_ID0 = CUSTOMER0 ), START_TIME0 >= SYSDATE0 ), START_TIME0 <= SYSDATE0 + 7 ) ), ( PRICE1 ) == ( PRICE0 ) ) ) ))
s.add( Not( And( Implies( True, And( ( SUM_OF_MAX0 ) == ( SUM_WEIGHT1 ), And( And( And( ( LOADS0 . LOAD_ID0 ) == ( LOAD_ID0 ), CUSTOMER_ID0 = CUSTOMER0 ), START_TIME0 >= SYSDATE0 ), START_TIME0 <= SYSDATE0 + 7 ) ) ), And( Implies( Or( PERCENT < 0, PERCENT > 100 ), ( WRONG_DISCOUNT1 ) == ( 1 ) ), And( Implies( Or( PERCENT < 0, PERCENT > 100 ), LOW_DISCOUNT1 == LOW_DISCOUNT0 ), And( Implies( Or( PERCENT < 0, PERCENT > 100 ), BIG_DISCOUNT1 == BIG_DISCOUNT0 ), And( Implies( Or( PERCENT < 0, PERCENT > 100 ), WRONG_DISCOUNT2 == WRONG_DISCOUNT1 ), And( Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( SUM_WEIGHT < 10, PERCENT > 50 ) ), ( BIG_DISCOUNT2 ) == ( 1 ) ), And( Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( SUM_WEIGHT < 10, PERCENT > 50 ) ), LOW_DISCOUNT1 == LOW_DISCOUNT0 ), And( Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( SUM_WEIGHT < 10, PERCENT > 50 ) ), BIG_DISCOUNT1 == BIG_DISCOUNT2 ), And( Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( SUM_WEIGHT < 10, PERCENT > 50 ) ), WRONG_DISCOUNT2 == WRONG_DISCOUNT0 ), And( Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ), ( LOW_DISCOUNT2 ) == ( 1 ) ), And( Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ), LOW_DISCOUNT1 == LOW_DISCOUNT2 ), And( Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ), BIG_DISCOUNT1 == BIG_DISCOUNT0 ), And( Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ), WRONG_DISCOUNT2 == WRONG_DISCOUNT0 ), And( Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ), ( WRONG_DISCOUNT3 ) == ( 0 ) ), And( Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ), ( BIG_DISCOUNT3 ) == ( 0 ) ), And( Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ), LOW_DISCOUNT1 == LOW_DISCOUNT0 ), And( Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ), BIG_DISCOUNT1 == BIG_DISCOUNT3 ), And( Implies( And( Not( Or( PERCENT < 0, PERCENT > 100 ) ), And( Not( And( SUM_WEIGHT < 10, PERCENT > 50 ) ), Not( And( SUM_WEIGHT > 30, PERCENT < 10 ) ) ) ), WRONG_DISCOUNT2 == WRONG_DISCOUNT3 ), Implies( True, Or( And( ( PRICE1 ) == ( PRICE0 * ( ( 100 - PERCENT0 ) / 100 ) ), And( And( And( ( ROUTES0 . LOAD_ID0 ) == ( LOAD_ID0 ), CUSTOMER_ID0 = CUSTOMER0 ), START_TIME0 >= SYSDATE0 ), START_TIME0 <= SYSDATE0 + 7 ) ), And( Not( And( And( And( ( ROUTES0 . LOAD_ID0 ) == ( LOAD_ID0 ), CUSTOMER_ID0 = CUSTOMER0 ), START_TIME0 >= SYSDATE0 ), START_TIME0 <= SYSDATE0 + 7 ) ), ( PRICE1 ) == ( PRICE0 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )

print()

print("------------------------------------------------------------------\nRunning script in /wpc/z3FormatWpcFile.py ....\n")

print("%%%%%%%%%% Aggregate Formula %%%%%%%%%%\n", s)

print()
print("%%%%%%%%%% Satisfiability %%%%%%%%%%\n", s.check())

print()
print("%%%%%%%%%% Satisfiable Model %%%%%%%%%%\n", s.model())

print()
