# This file was generated at runtime 
from z3 import *

D0 = Real('D0')
B1 = Real('B1')
A2 = Real('A2')
Y0 = Real('Y0')
B0 = Real('B0')
C3 = Real('C3')
X0 = Real('X0')
D2 = Real('D2')
X2 = Real('X2')
C1 = Real('C1')
C2 = Real('C2')
Z1 = Real('Z1')
A1 = Real('A1')
A3 = Real('A3')
C0 = Real('C0')
D3 = Real('D3')
X1 = Real('X1')
B3 = Real('B3')
D1 = Real('D1')
B2 = Real('B2')
A0 = Real('A0')

s = Solver()
s.add(True)
s.add(Implies( True, And( And( And( And( C0 + D0 < 0, A0 > 0 ), B0 > 0 ), C0 > 0 ), D0 > 0 ) ))
s.add(True)
s.add(Implies( True, ( X1 ) == ( X0 - 36 ) ))
s.add(True)
s.add(Implies( True, And( ( X2 ) == ( A0 ), A0 == X1 + 3 ) ))
s.add(True)
s.add(Implies( True, And( ( Z1 ) == ( B0 ), A0 == X1 + 3 ) ))
s.add(True)
s.add(Implies( True, ( A1 ) == ( X2 + 5 ) ))
s.add(True)
s.add(Implies( True, ( B1 ) == ( Y0 - 5 ) ))
s.add(True)
s.add(Implies( True, Or( And( And( ( A3 ) == ( A2 * ( X2 - 9 * ( Y0 - 3 ) ) ), ( B3 ) == ( Y0 - 9 ) ), And( A2 > 10, B2 <= ( X2 + Y0 ) - 50 ) ), And( Not( And( A2 > 10, B2 <= ( X2 + Y0 ) - 50 ) ), And( ( A3 ) == ( A2 ), ( B3 ) == ( B2 ) ) ) ) ))
s.add( Not( And( Implies( True, And( And( And( And( C0 + D0 < 0, A0 > 0 ), B0 > 0 ), C0 > 0 ), D0 > 0 ) ), And( Implies( True, ( X1 ) == ( X0 - 36 ) ), And( Implies( True, And( ( X2 ) == ( A0 ), A0 == X1 + 3 ) ), And( Implies( True, And( ( Z1 ) == ( B0 ), A0 == X1 + 3 ) ), And( Implies( True, ( A1 ) == ( X2 + 5 ) ), And( Implies( True, ( B1 ) == ( Y0 - 5 ) ), And( Implies( True, Or( And( And( ( A3 ) == ( A2 * ( X2 - 9 * ( Y0 - 3 ) ) ), ( B3 ) == ( Y0 - 9 ) ), And( A2 > 10, B2 <= ( X2 + Y0 ) - 50 ) ), And( Not( And( A2 > 10, B2 <= ( X2 + Y0 ) - 50 ) ), And( ( A3 ) == ( A2 ), ( B3 ) == ( B2 ) ) ) ) ), And( And( And( And( C3 + D3 < 0, A3 > 0 ), B3 > 0 ), C3 > 0 ), D3 > 0 ) ) ) ) ) ) ) ) ) )

print()

print("------------------------------------------------------------------\nRunning script in /wpc/z3FormatWpcFile.py ....\n")

print("%%%%%%%%%% Aggregate Formula %%%%%%%%%%\n", s)

print()
print("%%%%%%%%%% Satisfiability %%%%%%%%%%\n", s.check())

print()
print("%%%%%%%%%% Satisfiable Model %%%%%%%%%%\n", s.model())

print()
