CREATE OR REPLACE PROCEDURE TEMPORARY_WEEK_DISCOUNT(CUSTOMER IN CUSTOMERS.CUSTOMER_ID%TYPE, PERCENT INTEGER)
IS
	BIG_DISCOUNT EXCEPTION;
	LOW_DISCOUNT EXCEPTION;
	WRONG_DISCOUNT EXCEPTION;
	SUM_WEIGHT NUMBER(5,3);
BEGIN
	ASSUME BIG_DISCOUNT >= 0 AND LOW_DISCOUNT >= 0 AND WRONG_DISCOUNT >= 0 AND PRICE > 0 AND SYSDATE > 0 ;

	IF PERCENT < 0 OR PERCENT > 100 THEN
		RAISE WRONG_DISCOUNT;
	ELSIF PERCENT > 200 THEN
	  X := 1;
	END IF;
ASSERT BIG_DISCOUNT >= 0 AND LOW_DISCOUNT >= 0 AND WRONG_DISCOUNT >= 0 AND PRICE > 0 AND SYSDATE > 0 ;
	END TEMPORARY_WEEK_DISCOUNT;