CREATE OR REPLACE PROCEDURE TEST(X IN VARCHAR, Y IN VARCHAR)
IS
  BEGIN
	ASSUME A+P>=50 AND C+D=100 AND Q+R<54 ;


      X := X-50;
      SELECT A INTO K FROM T WHERE A=X+3 AND B=X-3;
      INSERT INTO T (A, B) VALUES (X+5, Y-5);
      DELETE FROM T WHERE A=X+8 AND B=Y-8;
      UPDATE T SET A=X-9 WHERE A>10;

  ASSERT A+P>=50 AND C+D=100 AND Q+R<54 ;
	END;