from z3 import *
ID0 = Real('ID0')
AMOUNT0 = Real('AMOUNT0')
PRICE0 = Real('PRICE0')
T_PRICE0 = Real('T_PRICE0')
T_ID0 = Real('T_ID0')
PRICE1 = Real('PRICE1')
PRICE2 = Real('PRICE2')
PRICE3 = Real('PRICE3')
T_PRICE1 = Real('T_PRICE1')
T_ID1 = Real('T_ID1')
T_AMOUNT1 = Real('T_AMOUNT1')
PRICE4 = Real('PRICE4')
PRICE5 = Real('PRICE5')
s = Solver()
s.add(And(And(And(And(And(And(And(And(True, And(And(AMOUNT0 > 0 , T_PRICE0 > 0 ), PRICE0 > 0 )), PRICE1 ==T_PRICE0 ), T_ID0 ==ID0 ), AMOUNT0 >= 1000 ), And(PRICE5  == PRICE1 - 0.1 * AMOUNT0 , PRICE3==PRICE5)), T_ID1  == ID0 ), T_PRICE1  == PRICE3 ), T_AMOUNT1  == AMOUNT0 ))
s.add(Not(Implies(And(And(And(And(And(And(And(And(True, And(And(AMOUNT0 > 0 , T_PRICE0 > 0 ), PRICE0 > 0 )), PRICE1 ==T_PRICE0 ), T_ID0 ==ID0 ), AMOUNT0 >= 1000 ), And(PRICE5  == PRICE1 - 0.1 * AMOUNT0 , PRICE3==PRICE5)), T_ID1  == ID0 ), T_PRICE1  == PRICE3 ), T_AMOUNT1  == AMOUNT0 ), PRICE3 > 0 )))
r = s.check()
if str(r) == "unsat":
    print("looksgood")
else:
    print("cannotsay")
